FROM gcr.io/dicectf-2022/jail-nightmare
COPY --from=ubuntu@sha256:cc8f713078bfddfe9ace41e29eb73298f52b2c958ccacd1b376b9378e20906ef / /srv
COPY bin/nightmare /srv/app/run
ENV JAIL_FLAG=dice{7H3_L1NK3r_15_4_C0mpL3x_5UrF4c3}
